# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app: go-web-app

image:
  user: a571
  name: go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "24287411673"

deployment:
  replicas: 1
  port: 8080

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  hosts:
  - host: abhishek.com
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: go-web-app
          port:
            number: 80